# Generated by Django 4.2.29 on 2026-03-13 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorProductMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("primary_mapping", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_mappings",
                        to="product.product",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_mappings",
                        to="vendor.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Product Mapping",
                "verbose_name_plural": "Vendor Product Mappings",
                "db_table": "vendor_product_mappings",
                "ordering": ["-created_at"],
                "unique_together": {("vendor", "product")},
            },
        ),
    ]
